export const mockForecastApiResponse = {
  "@context": [
    "https://geojson.org/geojson-ld/geojson-context.jsonld",
    {
      "@version": "1.1",
      wx: "https://api.weather.gov/ontology#",
      geo: "http://www.opengis.net/ont/geosparql#",
      unit: "http://codes.wmo.int/common/unit/",
      "@vocab": "https://api.weather.gov/ontology#",
    },
  ],
  type: "Feature",
  geometry: {
    type: "Polygon",
    coordinates: [
      [
        [-76.9036, 38.8422],
        [-76.8998, 38.864199899999996],
        [-76.928, 38.86709999999999],
        [-76.9318, 38.845099999999995],
        [-76.9036, 38.8422],
      ],
    ],
  },
  properties: {
    units: "us",
    forecastGenerator: "BaselineForecastGenerator",
    generatedAt: "2025-06-22T15:28:59+00:00",
    updateTime: "2025-06-22T14:31:41+00:00",
    validTimes: "2025-06-22T08:00:00+00:00/P7DT17H",
    elevation: {
      unitCode: "wmoUnit:m",
      value: 75.8952,
    },
    periods: [
      {
        number: 1,
        name: "Today",
        startTime: "2025-06-22T11:00:00-04:00",
        endTime: "2025-06-22T18:00:00-04:00",
        isDaytime: true,
        temperature: 97,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 2,
        },
        windSpeed: "7 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/day/hot?size=medium",
        shortForecast: "Sunny",
        detailedForecast:
          "Sunny, with a high near 97. Heat index values as high as 102. Southwest wind around 7 mph.",
      },
      {
        number: 2,
        name: "Tonight",
        startTime: "2025-06-22T18:00:00-04:00",
        endTime: "2025-06-23T06:00:00-04:00",
        isDaytime: false,
        temperature: 77,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 2,
        },
        windSpeed: "3 to 7 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/night/sct?size=medium",
        shortForecast: "Partly Cloudy",
        detailedForecast:
          "Partly cloudy, with a low around 77. Heat index values as high as 101. Southwest wind 3 to 7 mph.",
      },
      {
        number: 3,
        name: "Monday",
        startTime: "2025-06-23T06:00:00-04:00",
        endTime: "2025-06-23T18:00:00-04:00",
        isDaytime: true,
        temperature: 100,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 3,
        },
        windSpeed: "6 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/hot?size=medium",
        shortForecast: "Sunny",
        detailedForecast:
          "Sunny, with a high near 100. Heat index values as high as 108. Northwest wind around 6 mph.",
      },
      {
        number: 4,
        name: "Monday Night",
        startTime: "2025-06-23T18:00:00-04:00",
        endTime: "2025-06-24T06:00:00-04:00",
        isDaytime: false,
        temperature: 79,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 3,
        },
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast:
          "Mostly clear, with a low around 79. Heat index values as high as 106. West wind around 5 mph.",
      },
      {
        number: 5,
        name: "Tuesday",
        startTime: "2025-06-24T06:00:00-04:00",
        endTime: "2025-06-24T18:00:00-04:00",
        isDaytime: true,
        temperature: 101,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 4,
        },
        windSpeed: "2 to 6 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/hot?size=medium",
        shortForecast: "Sunny",
        detailedForecast:
          "Sunny, with a high near 101. Northwest wind 2 to 6 mph.",
      },
      {
        number: 6,
        name: "Tuesday Night",
        startTime: "2025-06-24T18:00:00-04:00",
        endTime: "2025-06-25T06:00:00-04:00",
        isDaytime: false,
        temperature: 79,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 6,
        },
        windSpeed: "6 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast: "Mostly clear, with a low around 79.",
      },
      {
        number: 7,
        name: "Wednesday",
        startTime: "2025-06-25T06:00:00-04:00",
        endTime: "2025-06-25T18:00:00-04:00",
        isDaytime: true,
        temperature: 98,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 19,
        },
        windSpeed: "6 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/hot/tsra_hi,20?size=medium",
        shortForecast:
          "Mostly Sunny then Slight Chance Showers And Thunderstorms",
        detailedForecast:
          "A slight chance of showers and thunderstorms after 2pm. Mostly sunny, with a high near 98.",
      },
      {
        number: 8,
        name: "Wednesday Night",
        startTime: "2025-06-25T18:00:00-04:00",
        endTime: "2025-06-26T06:00:00-04:00",
        isDaytime: false,
        temperature: 77,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 20,
        },
        windSpeed: "2 to 6 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/night/tsra_hi,20?size=medium",
        shortForecast: "Slight Chance Showers And Thunderstorms",
        detailedForecast:
          "A slight chance of showers and thunderstorms before 2am. Partly cloudy, with a low around 77.",
      },
      {
        number: 9,
        name: "Thursday",
        startTime: "2025-06-26T06:00:00-04:00",
        endTime: "2025-06-26T18:00:00-04:00",
        isDaytime: true,
        temperature: 96,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 33,
        },
        windSpeed: "2 to 6 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/sct/tsra_hi,30?size=medium",
        shortForecast: "Mostly Sunny then Chance Showers And Thunderstorms",
        detailedForecast:
          "A chance of showers and thunderstorms after 2pm. Mostly sunny, with a high near 96. Chance of precipitation is 30%.",
      },
      {
        number: 10,
        name: "Thursday Night",
        startTime: "2025-06-26T18:00:00-04:00",
        endTime: "2025-06-27T06:00:00-04:00",
        isDaytime: false,
        temperature: 75,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 33,
        },
        windSpeed: "6 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/tsra_hi,30?size=medium",
        shortForecast: "Chance Showers And Thunderstorms",
        detailedForecast:
          "A chance of showers and thunderstorms before 2am. Partly cloudy, with a low around 75. Chance of precipitation is 30%.",
      },
      {
        number: 11,
        name: "Friday",
        startTime: "2025-06-27T06:00:00-04:00",
        endTime: "2025-06-27T18:00:00-04:00",
        isDaytime: true,
        temperature: 90,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 32,
        },
        windSpeed: "3 to 7 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/day/sct/tsra_hi,30?size=medium",
        shortForecast: "Mostly Sunny then Chance Showers And Thunderstorms",
        detailedForecast:
          "A chance of showers and thunderstorms after 2pm. Mostly sunny, with a high near 90. Chance of precipitation is 30%.",
      },
      {
        number: 12,
        name: "Friday Night",
        startTime: "2025-06-27T18:00:00-04:00",
        endTime: "2025-06-28T06:00:00-04:00",
        isDaytime: false,
        temperature: 73,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 33,
        },
        windSpeed: "7 mph",
        windDirection: "SE",
        icon: "https://api.weather.gov/icons/land/night/tsra_hi,30?size=medium",
        shortForecast: "Chance Showers And Thunderstorms",
        detailedForecast:
          "A chance of showers and thunderstorms. Mostly cloudy, with a low around 73. Chance of precipitation is 30%.",
      },
      {
        number: 13,
        name: "Saturday",
        startTime: "2025-06-28T06:00:00-04:00",
        endTime: "2025-06-28T18:00:00-04:00",
        isDaytime: true,
        temperature: 88,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 33,
        },
        windSpeed: "7 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/day/rain_showers,20/tsra_hi,30?size=medium",
        shortForecast:
          "Slight Chance Rain Showers then Chance Showers And Thunderstorms",
        detailedForecast:
          "A slight chance of rain showers before 8am, then a chance of showers and thunderstorms. Partly sunny, with a high near 88. Chance of precipitation is 30%.",
      },
      {
        number: 14,
        name: "Saturday Night",
        startTime: "2025-06-28T18:00:00-04:00",
        endTime: "2025-06-29T06:00:00-04:00",
        isDaytime: false,
        temperature: 71,
        temperatureUnit: "F",
        temperatureTrend: "",
        probabilityOfPrecipitation: {
          unitCode: "wmoUnit:percent",
          value: 33,
        },
        windSpeed: "3 to 7 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/night/tsra_hi,30?size=medium",
        shortForecast: "Chance Showers And Thunderstorms",
        detailedForecast:
          "A chance of showers and thunderstorms before 8pm, then a chance of showers and thunderstorms. Mostly cloudy, with a low around 71.",
      },
    ],
  },
};

export const mockForecast = {
  generatedAt: "2025-06-22T15:28:59+00:00",
  updateTime: "2025-06-22T14:31:41+00:00",
  periods: [
    {
      number: 1,
      name: "Today",
      startTime: "2025-06-22T11:00:00-04:00",
      endTime: "2025-06-22T18:00:00-04:00",
      isDaytime: true,
      temperature: 97,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 2,
      },
      windSpeed: "7 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/day/hot?size=medium",
      shortForecast: "Sunny",
      detailedForecast:
        "Sunny, with a high near 97. Heat index values as high as 102. Southwest wind around 7 mph.",
    },
    {
      number: 2,
      name: "Tonight",
      startTime: "2025-06-22T18:00:00-04:00",
      endTime: "2025-06-23T06:00:00-04:00",
      isDaytime: false,
      temperature: 77,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 2,
      },
      windSpeed: "3 to 7 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/night/sct?size=medium",
      shortForecast: "Partly Cloudy",
      detailedForecast:
        "Partly cloudy, with a low around 77. Heat index values as high as 101. Southwest wind 3 to 7 mph.",
    },
    {
      number: 3,
      name: "Monday",
      startTime: "2025-06-23T06:00:00-04:00",
      endTime: "2025-06-23T18:00:00-04:00",
      isDaytime: true,
      temperature: 100,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 3,
      },
      windSpeed: "6 mph",
      windDirection: "NW",
      icon: "https://api.weather.gov/icons/land/day/hot?size=medium",
      shortForecast: "Sunny",
      detailedForecast:
        "Sunny, with a high near 100. Heat index values as high as 108. Northwest wind around 6 mph.",
    },
    {
      number: 4,
      name: "Monday Night",
      startTime: "2025-06-23T18:00:00-04:00",
      endTime: "2025-06-24T06:00:00-04:00",
      isDaytime: false,
      temperature: 79,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 3,
      },
      windSpeed: "5 mph",
      windDirection: "W",
      icon: "https://api.weather.gov/icons/land/night/few?size=medium",
      shortForecast: "Mostly Clear",
      detailedForecast:
        "Mostly clear, with a low around 79. Heat index values as high as 106. West wind around 5 mph.",
    },
    {
      number: 5,
      name: "Tuesday",
      startTime: "2025-06-24T06:00:00-04:00",
      endTime: "2025-06-24T18:00:00-04:00",
      isDaytime: true,
      temperature: 101,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 4,
      },
      windSpeed: "2 to 6 mph",
      windDirection: "NW",
      icon: "https://api.weather.gov/icons/land/day/hot?size=medium",
      shortForecast: "Sunny",
      detailedForecast:
        "Sunny, with a high near 101. Northwest wind 2 to 6 mph.",
    },
    {
      number: 6,
      name: "Tuesday Night",
      startTime: "2025-06-24T18:00:00-04:00",
      endTime: "2025-06-25T06:00:00-04:00",
      isDaytime: false,
      temperature: 79,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 6,
      },
      windSpeed: "6 mph",
      windDirection: "NW",
      icon: "https://api.weather.gov/icons/land/night/few?size=medium",
      shortForecast: "Mostly Clear",
      detailedForecast: "Mostly clear, with a low around 79.",
    },
    {
      number: 7,
      name: "Wednesday",
      startTime: "2025-06-25T06:00:00-04:00",
      endTime: "2025-06-25T18:00:00-04:00",
      isDaytime: true,
      temperature: 98,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 19,
      },
      windSpeed: "6 mph",
      windDirection: "NW",
      icon: "https://api.weather.gov/icons/land/day/hot/tsra_hi,20?size=medium",
      shortForecast:
        "Mostly Sunny then Slight Chance Showers And Thunderstorms",
      detailedForecast:
        "A slight chance of showers and thunderstorms after 2pm. Mostly sunny, with a high near 98.",
    },
    {
      number: 8,
      name: "Wednesday Night",
      startTime: "2025-06-25T18:00:00-04:00",
      endTime: "2025-06-26T06:00:00-04:00",
      isDaytime: false,
      temperature: 77,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 20,
      },
      windSpeed: "2 to 6 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/night/tsra_hi,20?size=medium",
      shortForecast: "Slight Chance Showers And Thunderstorms",
      detailedForecast:
        "A slight chance of showers and thunderstorms before 2am. Partly cloudy, with a low around 77.",
    },
    {
      number: 9,
      name: "Thursday",
      startTime: "2025-06-26T06:00:00-04:00",
      endTime: "2025-06-26T18:00:00-04:00",
      isDaytime: true,
      temperature: 96,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 33,
      },
      windSpeed: "2 to 6 mph",
      windDirection: "NW",
      icon: "https://api.weather.gov/icons/land/day/sct/tsra_hi,30?size=medium",
      shortForecast: "Mostly Sunny then Chance Showers And Thunderstorms",
      detailedForecast:
        "A chance of showers and thunderstorms after 2pm. Mostly sunny, with a high near 96. Chance of precipitation is 30%.",
    },
    {
      number: 10,
      name: "Thursday Night",
      startTime: "2025-06-26T18:00:00-04:00",
      endTime: "2025-06-27T06:00:00-04:00",
      isDaytime: false,
      temperature: 75,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 33,
      },
      windSpeed: "6 mph",
      windDirection: "N",
      icon: "https://api.weather.gov/icons/land/night/tsra_hi,30?size=medium",
      shortForecast: "Chance Showers And Thunderstorms",
      detailedForecast:
        "A chance of showers and thunderstorms before 2am. Partly cloudy, with a low around 75. Chance of precipitation is 30%.",
    },
    {
      number: 11,
      name: "Friday",
      startTime: "2025-06-27T06:00:00-04:00",
      endTime: "2025-06-27T18:00:00-04:00",
      isDaytime: true,
      temperature: 90,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 32,
      },
      windSpeed: "3 to 7 mph",
      windDirection: "E",
      icon: "https://api.weather.gov/icons/land/day/sct/tsra_hi,30?size=medium",
      shortForecast: "Mostly Sunny then Chance Showers And Thunderstorms",
      detailedForecast:
        "A chance of showers and thunderstorms after 2pm. Mostly sunny, with a high near 90. Chance of precipitation is 30%.",
    },
    {
      number: 12,
      name: "Friday Night",
      startTime: "2025-06-27T18:00:00-04:00",
      endTime: "2025-06-28T06:00:00-04:00",
      isDaytime: false,
      temperature: 73,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 33,
      },
      windSpeed: "7 mph",
      windDirection: "SE",
      icon: "https://api.weather.gov/icons/land/night/tsra_hi,30?size=medium",
      shortForecast: "Chance Showers And Thunderstorms",
      detailedForecast:
        "A chance of showers and thunderstorms. Mostly cloudy, with a low around 73. Chance of precipitation is 30%.",
    },
    {
      number: 13,
      name: "Saturday",
      startTime: "2025-06-28T06:00:00-04:00",
      endTime: "2025-06-28T18:00:00-04:00",
      isDaytime: true,
      temperature: 88,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 33,
      },
      windSpeed: "7 mph",
      windDirection: "E",
      icon: "https://api.weather.gov/icons/land/day/rain_showers,20/tsra_hi,30?size=medium",
      shortForecast:
        "Slight Chance Rain Showers then Chance Showers And Thunderstorms",
      detailedForecast:
        "A slight chance of rain showers before 8am, then a chance of showers and thunderstorms. Partly sunny, with a high near 88. Chance of precipitation is 30%.",
    },
    {
      number: 14,
      name: "Saturday Night",
      startTime: "2025-06-28T18:00:00-04:00",
      endTime: "2025-06-29T06:00:00-04:00",
      isDaytime: false,
      temperature: 71,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 33,
      },
      windSpeed: "3 to 7 mph",
      windDirection: "E",
      icon: "https://api.weather.gov/icons/land/night/tsra_hi,30?size=medium",
      shortForecast: "Chance Showers And Thunderstorms",
      detailedForecast:
        "A chance of showers and thunderstorms before 8pm, then a chance of showers and thunderstorms. Mostly cloudy, with a low around 71.",
    },
  ],
};
